spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/migration/db.changelog-master.yml