spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/migration/db.changelog-master.yml
  http:
    client:
      connect-timeout: 3s
      read-timeout: 10s

speller:
  base-url: https://speller.yandex.net/services/spellservice.json
